// frontend/src/components/Login.jsx
import axios from 'axios';
import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'

function Login() {
    const [formData, setFormData] = useState({
        email: '',
        password: ''
    });

    const Navigate = useNavigate();

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    }

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post('http://localhost:4000/user/login', formData);

            console.log("Full API Response:", response.data); // Debugging

            const { userName, role, email, token } = response.data;

            alert("Login Successful");

            // Store role in localStorage
            localStorage.setItem("role", JSON.stringify(role));
            localStorage.setItem("token", JSON.stringify(token));
            e.target.reset();
            Navigate('/'); //Navigate to the home page
        } catch (error) {
            const errorMessage = error.response?.data?.message || error.message;
            console.log("Login error:", errorMessage);
            alert(errorMessage);
        }
    };

    return (
        <>

            <div className='w-full h-screen bg-gray-300'>
                <div className='flex justify-center items-center '>

                    <div className='flex justify-center items-center bg-white rounded mt-24'>
                        
                        <form onSubmit={handleSubmit} className="w-72 md:w-96 p-4 flex flex-col gap-4" >

                            <label> email :</label>
                            <input type="email" name='email' placeholder='Enter Email' className='border p-1' onChange={handleChange} required />

                            <label> Password :</label>
                            <input type="text" name='password' placeholder='Enter Password' className='border p-1' onChange={handleChange} required />
                            <div className='flex justify-center'>
                                <button type='submit' className='bg-blue-600 rounded text-white px-8 py-2 mt-2'>Login</button>
                            </div>
                            <Link to='/signup' className='flex justify-center mt-2'><p>Don't have an account?</p></Link>
                        </form>
                    </div>
                </div>
            </div>

        </>
    )
}

export default Login

// src/app/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  loginForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
    });
  }


  
  login() {
    if (this.loginForm.valid) {
      const { email, password } = this.loginForm.value;
      this.authService.login(email, password).subscribe(
        (response) => {
          localStorage.setItem('token', response.token);
          this.router.navigate(['/todo']);
          // alert('login successful!')
        },
        (error) => {
          alert('Login failed: ' + (error.message || error));
        }
      );
    } else {
      alert('Please fill out the form correctly.');
    }
  }

  logout() {
    localStorage.removeItem('token');
    this.router.navigate(['/login']);
  }
}

<div class="min-h-screen flex items-center justify-center bg-gray-300">
  <div class="grid md:grid-cols-2 mt-12  shadow-gray-500 shadow-lg">

    <div class="md:bg-blue-400 md:py-12 md:px-8">
      <img src="../../../assets/images/login-img.png " alt="Signup-img" class="w-80 h-80 hidden md:block ">
    </div>

    <div class="w-full max-w-md bg-white p-8 shadow-md">
      <h2 class="text-2xl font-semibold text-center mb-6"><i class="fa-solid fa-key text-green-700"></i> Login </h2>
      <form [formGroup]="loginForm" (ngSubmit)="login()">
        <div class="mb-4">
          <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
          <input type="email" id="email" formControlName="email" placeholder="Enter Email"
            class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500" />
          <div *ngIf="loginForm.get('email')?.touched && loginForm.get('email')?.invalid">
            <small *ngIf="loginForm.get('email')?.errors?.['required']" class="text-red-500">
              Email is required.
            </small>
            <small *ngIf="loginForm.get('email')?.errors?.['email']" class="text-red-500">
              Please enter a valid email address.
            </small>
          </div>
        </div>
        <div class="mb-4">
          <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
          <input type="password" id="password" formControlName="password" placeholder="Enter Password"
            class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500" />
          <div *ngIf="loginForm.get('password')?.touched && loginForm.get('password')?.invalid">
            <small *ngIf="loginForm.get('password')?.errors?.['required']" class="text-red-500">
              Password is required.
            </small>
            <small *ngIf="loginForm.get('password')?.errors?.['minlength']" class="text-red-500">
              Password must be at least 6 characters long.
            </small>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="w-full py-2 bg-blue-500 text-white font-semibold rounded-md hover:bg-blue-600"
            [disabled]="loginForm.invalid">
            Login
          </button>
        </div>
      </form>
      <div class="mt-4 text-center">
        <p>Don't have an account? <a routerLink="/auth/signup" class="text-blue-500 hover:underline">Sign up</a></p>
      </div>
    </div>
  </div>

</div>
