// src/app/auth/signup/signup.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
})
export class SignupComponent {
  signUpForm: FormGroup;
  successMessage = '';
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.signUpForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
    });
  }

  signUp() {
    this.successMessage = '';
    this.errorMessage = '';

    if (this.signUpForm.valid) {
      const user = this.signUpForm.value;
      this.authService.signUp(user).subscribe(
        (response) => {
          this.router.navigate(['/auth/login']);

          this.successMessage = ' successfully Signup !';
          setTimeout(() => {
            this.successMessage = '';
          }, 3000);
        },
        (error) => {
          console.error('Signup error:', error);
          alert('Signup failed: ' + (error.message || error));
        }
      );
    } else {
      alert('Please fill out the form correctly.');
    }
  }
}

<div class="min-h-screen flex items-center justify-center bg-gray-300 ">


  <div class="toast toast-top toast-end mt-16 ">
    <div *ngIf="errorMessage"  class="alert alert-info bg-red-600">
      <span><p class="error text-white bg-red-600 text-center">{{ errorMessage }}</p>
      </span>
    </div>
    <div *ngIf="successMessage" class="alert alert-success">
      <span>  <p  class="success text-white text-center">{{ successMessage }}</p></span>
    </div>
  </div>

  <div class="grid md:grid-cols-2 mt-12  shadow-gray-500 shadow-lg ">

    <div class="">
      <img src="../../../assets/images/signup-img.png " alt="Signup-img" class="w-96  h-full hidden md:block bg-orange-500">
    </div>

    <div class="w-full max-w-md bg-white p-8 ">
      <h2 class="text-2xl font-semibold text-center mb-6"><i class="fa-solid fa-circle-user  text-center text-yellow-400"></i> Sign Up</h2>
      <form [formGroup]="signUpForm" (ngSubmit)="signUp()" class="md:mt-10">
        <div class="mb-4 gap-4">
          <div class="mb-4">
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" id="name" formControlName="email" placeholder="Enter Name"
              class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500" />
          </div>
          <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
          <input type="email" id="email" formControlName="email" placeholder="Enter Email"
            class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500" />
          <div *ngIf="signUpForm.get('email')?.touched && signUpForm.get('email')?.invalid">
            <small *ngIf="signUpForm.get('email')?.errors?.['required']" class="text-red-500">
              Email is required.
            </small>
            <small *ngIf="signUpForm.get('email')?.errors?.['email']" class="text-red-500">
              Please enter a valid email.
            </small>
          </div>
        </div>
        <div class="mb-4">
          <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
          <input type="password" id="password" formControlName="password" placeholder="Enter Password"
            class="mt-1 p-2 w-full border rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500" />
          <div *ngIf="signUpForm.get('password')?.touched && signUpForm.get('password')?.invalid">
            <small *ngIf="signUpForm.get('password')?.errors?.['required']" class="text-red-500">
              Password is required.
            </small>
            <small *ngIf="signUpForm.get('password')?.errors?.['minlength']" class="text-red-500">
              Password must be at least 6 characters long.
            </small>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="w-full py-2 bg-blue-500 text-white font-semibold rounded-md hover:bg-blue-600"
            [disabled]="signUpForm.invalid">
            Sign Up
          </button>
        </div>
      </form>
      <div class="mt-4 text-center">
        <p>Already have an account? <a routerLink="/auth/login" class="text-blue-500 hover:underline">Login</a></p>
      </div>
    </div>
  </div>
</div>

// frontend/src/components/Signup.jsx
import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import axios from "axios";
function Signup() {
    const [formData, setFormData] = useState({
        userName: '',
        email: '',
        password: '',
        role: 'user'
    })

    const Navigate = useNavigate();

    // handle Input change
    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value })
    }
    // handle form submit
    const handleSubmit = async (e) => {
        e.preventDefault();

        await axios.post('http://localhost:4000/user/signup', formData)
            .then((res) => {
                console.log(res.data);
                console.log(formData.role);

                // Save user details
                // localStorage.setItem("user",JSON.stringify(res.data))
                // localStorage.setItem("Role",JSON.stringify(formData.role))
                alert('Signup successful');

                // reset form;
                e.target.reset();
                Navigate('/login'); //Navigate to the Login page
            })
            .catch((error) => {
                const errorMessage = error.response?.data?.message || error.message;
                console.log("Signup error:", errorMessage);
                alert("signup error " + errorMessage);
            });

    }


    return (
        <>
            <div className='w-full h-screen bg-gray-300'>
                <div className='flex justify-center items-center '>

                    <div className='flex justify-center items-center bg-white rounded mt-24'>

                        <form onSubmit={handleSubmit} className='w-72 md:w-96 p-4 flex flex-col gap-4' >
                            <label> Name :</label>
                            <input type="text" name="userName" placeholder='Enter Name' className='border p-1' onChange={handleChange} required />

                            <label> email :</label>
                            <input type="email" name='email' placeholder='Enter Email' className='border p-1' onChange={handleChange} required />

                            <label> Password :</label>
                            <input type="text" name='password' placeholder='Enter Password' className='border p-1' onChange={handleChange} required />

                            <div className='flex gap-4'>
                                <span>Role: </span>
                                <label htmlFor="">
                                    <input type="radio" name='role' value="user" checked={formData.role === 'user'} placeholder='Enter Password' onChange={handleChange} required />
                                    User
                                </label>
                                <label htmlFor="">
                                    <input type="radio" name='role' value="admin" checked={formData.role === 'admin'} placeholder='Enter Password' onChange={handleChange} required />
                                    Admin
                                </label>
                            </div>
                            <div className='flex justify-center'>
                                <button type='submit' className='bg-blue-600 rounded text-white px-8 py-2 mt-2'>Signup</button>
                            </div>
                            <div className='flex justify-center'>
                                <Link to='/login'><p>Already have an account?</p></Link>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </>
    );
}

export default Signup
